# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartAttendance' do
    
  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  use_frameworks!
    pod 'IQKeyboardManagerSwift'
    pod 'PopupDialog'
end
